/**
 * API validation schemas — barrel re-exports.
 *
 * Schemas are organized by feature under `src/features/<feature>/validation/schemas.ts`.
 * Shared primitives and enums live in `src/features/shared/validation/`.
 *
 * Base Prisma schemas are auto-generated from schema.prisma via prisma-zod-generator.
 * When the Prisma schema changes, run `prisma generate` to update generated schemas.
 */

export {
  CurrencySchema,
  PaymentMethodSchema,
  TransactionTypeSchema,
  MessageTypeSchema,
  TimePrecisionSchema,
  getCurrencyOptions,
  type ICurrency,
  type IPaymentMethod,
  type ITransactionType,
  type IMessageType,
  type ITimePrecision,
} from "@/features/shared/validation/enums";

export {
  ISODateStringSchema,
  DateStringSchema,
  DecimalStringSchema,
  PaginationQuerySchema,
  SortQuerySchema,
} from "@/features/shared/validation/primitives";

export { ErrorResponseSchema, type IErrorResponse } from "@/features/shared/validation/error";

export {
  TransactionTagSchema,
  TagSchema,
  FORBIDDEN_COLORS,
  CreateTagInputSchema,
  UpdateTagInputSchema,
  TagMetadataSchema,
  ReorderTagsInputSchema,
  TagsQuerySchema,
  TagsResponseSchema,
  BulkCreateTagInputSchema,
  BulkCreateTagErrorSchema,
  BulkCreateTagResponseSchema,
  TagCsvUploadResponseSchema,
  TagCsvFieldMappingSchema,
  TagCsvMappingValidationSchema,
  TagCsvParseRequestSchema,
  TagCsvCandidateErrorSchema,
  TagCsvCandidateSchema,
  TagCsvParseResponseSchema,
  TagCsvImportRequestSchema,
  TagCsvImportResponseSchema,
  type ITag,
  type ITagMetadata,
  type ICreateTagInput,
  type IUpdateTagInput,
  type IReorderTagsInput,
  type ITagsQuery,
  type ITagsResponse,
  type IBulkCreateTagInput,
  type IBulkCreateTagResponse,
  type ITagCsvUploadResponse,
  type ITagCsvFieldMapping,
  type ITagCsvMappingValidation,
  type ITagCsvParseRequest,
  type ITagCsvCandidate,
  type ITagCsvParseResponse,
  type ITagCsvImportRequest,
  type ITagCsvImportResponse,
} from "@/features/tag/validation/schemas";

export {
  TagRulePatternTypeSchema,
  TagRuleMatchFieldSchema,
  TagRuleApplyAsSchema,
  TagRuleSourceSchema,
  TagRuleSchema,
  CreateTagRuleInputSchema,
  UpdateTagRuleInputSchema,
  TagRulesResponseSchema,
  TagMatchRequestSchema,
  TagMatchResultSchema,
  TagMatchResponseSchema,
  TagHistoryDiscoverySchema,
  TagHistoryDiscoveryResponseSchema,
  EnableTagRulePresetsInputSchema,
  TagSuggestionRuleSchema,
  TagSuggestionsSchema,
  type ITagRule,
  type ICreateTagRuleInput,
  type IUpdateTagRuleInput,
  type ITagRulesResponse,
  type ITagMatchRequest,
  type ITagMatchResult,
  type ITagMatchResponse,
  type ITagHistoryDiscovery,
  type ITagHistoryDiscoveryResponse,
  type IEnableTagRulePresetsInput,
  type ITagSuggestions,
  type ITagSuggestionRule,
  type ITagRulePatternType,
  type ITagRuleMatchField,
  type ITagRuleApplyAs,
  type ITagRuleSource,
} from "@/features/tag-rule/validation/schemas";

export {
  TransactionSubscriptionInfoSchema,
  TransactionSchema,
  CreateTransactionInputSchema,
  UpdateTransactionInputSchema,
  TransactionsQuerySchema,
  PaginatedTransactionsResponseSchema,
  BulkCreateTransactionInputSchema,
  BulkCreateTransactionErrorSchema,
  BulkCreateTransactionResponseSchema,
  CsvUploadResponseSchema,
  CsvFieldMappingSchema,
  CsvMappingValidationSchema,
  CsvCandidateTransactionErrorSchema,
  CsvCandidateTransactionSchema,
  CsvTransformRequestSchema,
  CsvTransformResponseSchema,
  CsvImportRequestSchema,
  CsvImportResponseSchema,
  type ITransaction,
  type ICreateTransactionInput,
  type IUpdateTransactionInput,
  type ITransactionsQuery,
  type IPaginatedTransactionsResponse,
  type IBulkCreateTransactionInput,
  type IBulkCreateTransactionResponse,
  type ITransactionSubscriptionInfo,
  type ICsvUploadResponse,
  type ICsvFieldMapping,
  type ICsvMappingValidation,
  type ICsvCandidateTransaction,
  type ICsvTransformRequest,
  type ICsvTransformResponse,
  type ICsvImportRequest,
  type ICsvImportResponse,
} from "@/features/transaction/validation/schemas";

export {
  WorkspaceSummarySchema,
  CreateWorkspaceBodySchema,
  RenameWorkspaceBodySchema,
  WorkspaceSettingSchema,
  UpdateWorkspaceSettingInputSchema,
  type IWorkspaceSummary,
  type IWorkspaceSetting,
  type IUpdateWorkspaceSettingInput,
} from "@/features/workspace/validation/schemas";

export {
  formatFullName,
  UserSchema,
  ThemeSchema,
  UserSettingSchema,
  UpdateUserSettingInputSchema,
  UserResponseSchema,
  UserProfileSchema,
  UserProfileResponseSchema,
  UpdateUserProfileInputSchema,
  ConnectedAccountSchema,
  ConnectedAccountsResponseSchema,
  ChangePasswordInputSchema,
  ChangeEmailInputSchema,
  type IUser,
  type ITheme,
  type IUserSetting,
  type IUpdateUserSettingInput,
  type IUserResponse,
  type IUserProfile,
  type IUpdateUserProfileInput,
  type IConnectedAccount,
  type IConnectedAccountsResponse,
  type IChangePasswordInput,
  type IChangeEmailInput,
} from "@/features/users/validation/schemas";

export {
  MessageActionSchema,
  MessageSchema,
  CreateMessageInputSchema,
  UpdateMessageInputSchema,
  MessagesQuerySchema,
  MessagesResponseSchema,
  UnreadCountResponseSchema,
  type IMessage,
  type IMessageAction,
  type ICreateMessageInput,
  type IUpdateMessageInput,
  type IMessagesQuery,
  type IMessagesResponse,
  type IUnreadCountResponse,
} from "@/features/message/validation/schemas";

export {
  BudgetPresetSchema,
  BudgetPeriodTypeSchema,
  BudgetItemMonthlyAmountSchema,
  BudgetItemSchema,
  BudgetSchema,
  CreateBudgetItemMonthlyAmountInputSchema,
  CreateBudgetItemInputSchema,
  CreateBudgetInputSchema,
  UpdateBudgetInputSchema,
  BudgetsQuerySchema,
  BudgetsResponseSchema,
  BudgetItemComparisonSchema,
  BudgetMonthlyItemComparisonSchema,
  BudgetCategoryTotalsSchema,
  BudgetTotalsSchema,
  BudgetMonthlyBreakdownSchema,
  BudgetAlertSchema,
  BudgetComparisonSchema,
  BudgetsOverviewResponseSchema,
  type IBudgetPreset,
  type IBudgetPeriodType,
  type IBudgetItemMonthlyAmount,
  type IBudget,
  type IBudgetItem,
  type ICreateBudgetInput,
  type ICreateBudgetItemInput,
  type ICreateBudgetItemMonthlyAmountInput,
  type IUpdateBudgetInput,
  type IBudgetsQuery,
  type IBudgetsResponse,
  type IBudgetItemComparison,
  type IBudgetMonthlyItemComparison,
  type IBudgetMonthlyBreakdown,
  type IBudgetCategoryTotals,
  type IBudgetTotals,
  type IBudgetAlert,
  type IBudgetComparison,
  type IBudgetsOverviewResponse,
} from "@/features/budget/validation/schemas";

export {
  SubscriptionFrequencySchema,
  SubscriptionTransactionSchema,
  SubscriptionSchema,
  SubscriptionCandidateSchema,
  DetectSubscriptionsResponseSchema,
  DetectSubscriptionsOptionsSchema,
  ConfirmSubscriptionInputSchema,
  DismissSubscriptionCandidateInputSchema,
  UpdateSubscriptionInputSchema,
  SubscriptionsQuerySchema,
  SubscriptionsResponseSchema,
  SubscriptionDismissalSchema,
  SubscriptionDismissalsResponseSchema,
  type ISubscriptionFrequency,
  type ISubscription,
  type ISubscriptionTransaction,
  type ISubscriptionCandidate,
  type IDetectSubscriptionsResponse,
  type IDetectSubscriptionsOptions,
  type IConfirmSubscriptionInput,
  type IDismissSubscriptionCandidateInput,
  type IUpdateSubscriptionInput,
  type ISubscriptionsQuery,
  type ISubscriptionsResponse,
  type ISubscriptionDismissal,
  type ISubscriptionDismissalsResponse,
} from "@/features/subscription/validation/schemas";
