/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appTagsRouteImport } from './routes/(app)/tags'
import { Route as appIncomesRouteImport } from './routes/(app)/incomes'
import { Route as appExpensesRouteImport } from './routes/(app)/expenses'
import { Route as appAccountRouteImport } from './routes/(app)/account'
import { Route as ApiV1TransactionsRouteImport } from './routes/api/v1/transactions'
import { Route as ApiV1TagsRouteImport } from './routes/api/v1/tags'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1TransactionsCsvUploadRouteImport } from './routes/api/v1/transactions.csv-upload'
import { Route as ApiV1TransactionsCsvTransformRouteImport } from './routes/api/v1/transactions.csv-transform'
import { Route as ApiV1TransactionsCsvMappingRouteImport } from './routes/api/v1/transactions.csv-mapping'
import { Route as ApiV1TransactionsCsvImportRouteImport } from './routes/api/v1/transactions.csv-import'
import { Route as ApiV1TransactionsBulkRouteImport } from './routes/api/v1/transactions.bulk'
import { Route as ApiV1TransactionsTransactionIdRouteImport } from './routes/api/v1/transactions.$transactionId'
import { Route as ApiV1TagsReorderRouteImport } from './routes/api/v1/tags.reorder'
import { Route as ApiV1TagsCsvUploadRouteImport } from './routes/api/v1/tags.csv-upload'
import { Route as ApiV1TagsCsvParseRouteImport } from './routes/api/v1/tags.csv-parse'
import { Route as ApiV1TagsCsvMappingRouteImport } from './routes/api/v1/tags.csv-mapping'
import { Route as ApiV1TagsCsvImportRouteImport } from './routes/api/v1/tags.csv-import'
import { Route as ApiV1TagsBulkRouteImport } from './routes/api/v1/tags.bulk'
import { Route as ApiV1TagsTagIdRouteImport } from './routes/api/v1/tags.$tagId'
import { Route as ApiV1MeProfileRouteImport } from './routes/api/v1/me.profile'
import { Route as ApiV1MeAccountsRouteImport } from './routes/api/v1/me.accounts'
import { Route as ApiV1TransactionsCsvMappingValidateRouteImport } from './routes/api/v1/transactions.csv-mapping.validate'
import { Route as ApiV1TagsCsvMappingValidateRouteImport } from './routes/api/v1/tags.csv-mapping.validate'
import { Route as ApiV1MeAccountsAccountIdRouteImport } from './routes/api/v1/me.accounts.$accountId'
import { Route as ApiV1TransactionsTransactionIdTagsTagIdRouteImport } from './routes/api/v1/transactions.$transactionId.tags.$tagId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appTagsRoute = appTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => appRouteRoute,
} as any)
const appIncomesRoute = appIncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => appRouteRoute,
} as any)
const appExpensesRoute = appExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => appRouteRoute,
} as any)
const appAccountRoute = appAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiV1TransactionsRoute = ApiV1TransactionsRouteImport.update({
  id: '/api/v1/transactions',
  path: '/api/v1/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TagsRoute = ApiV1TagsRouteImport.update({
  id: '/api/v1/tags',
  path: '/api/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TransactionsCsvUploadRoute =
  ApiV1TransactionsCsvUploadRouteImport.update({
    id: '/csv-upload',
    path: '/csv-upload',
    getParentRoute: () => ApiV1TransactionsRoute,
  } as any)
const ApiV1TransactionsCsvTransformRoute =
  ApiV1TransactionsCsvTransformRouteImport.update({
    id: '/csv-transform',
    path: '/csv-transform',
    getParentRoute: () => ApiV1TransactionsRoute,
  } as any)
const ApiV1TransactionsCsvMappingRoute =
  ApiV1TransactionsCsvMappingRouteImport.update({
    id: '/csv-mapping',
    path: '/csv-mapping',
    getParentRoute: () => ApiV1TransactionsRoute,
  } as any)
const ApiV1TransactionsCsvImportRoute =
  ApiV1TransactionsCsvImportRouteImport.update({
    id: '/csv-import',
    path: '/csv-import',
    getParentRoute: () => ApiV1TransactionsRoute,
  } as any)
const ApiV1TransactionsBulkRoute = ApiV1TransactionsBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiV1TransactionsRoute,
} as any)
const ApiV1TransactionsTransactionIdRoute =
  ApiV1TransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => ApiV1TransactionsRoute,
  } as any)
const ApiV1TagsReorderRoute = ApiV1TagsReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsCsvUploadRoute = ApiV1TagsCsvUploadRouteImport.update({
  id: '/csv-upload',
  path: '/csv-upload',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsCsvParseRoute = ApiV1TagsCsvParseRouteImport.update({
  id: '/csv-parse',
  path: '/csv-parse',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsCsvMappingRoute = ApiV1TagsCsvMappingRouteImport.update({
  id: '/csv-mapping',
  path: '/csv-mapping',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsCsvImportRoute = ApiV1TagsCsvImportRouteImport.update({
  id: '/csv-import',
  path: '/csv-import',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsBulkRoute = ApiV1TagsBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1TagsTagIdRoute = ApiV1TagsTagIdRouteImport.update({
  id: '/$tagId',
  path: '/$tagId',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1MeProfileRoute = ApiV1MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1MeAccountsRoute = ApiV1MeAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1TransactionsCsvMappingValidateRoute =
  ApiV1TransactionsCsvMappingValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ApiV1TransactionsCsvMappingRoute,
  } as any)
const ApiV1TagsCsvMappingValidateRoute =
  ApiV1TagsCsvMappingValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ApiV1TagsCsvMappingRoute,
  } as any)
const ApiV1MeAccountsAccountIdRoute =
  ApiV1MeAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ApiV1MeAccountsRoute,
  } as any)
const ApiV1TransactionsTransactionIdTagsTagIdRoute =
  ApiV1TransactionsTransactionIdTagsTagIdRouteImport.update({
    id: '/tags/$tagId',
    path: '/tags/$tagId',
    getParentRoute: () => ApiV1TransactionsTransactionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof appAccountRoute
  '/expenses': typeof appExpensesRoute
  '/incomes': typeof appIncomesRoute
  '/tags': typeof appTagsRoute
  '/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/transactions': typeof ApiV1TransactionsRouteWithChildren
  '/api/v1/me/accounts': typeof ApiV1MeAccountsRouteWithChildren
  '/api/v1/me/profile': typeof ApiV1MeProfileRoute
  '/api/v1/tags/$tagId': typeof ApiV1TagsTagIdRoute
  '/api/v1/tags/bulk': typeof ApiV1TagsBulkRoute
  '/api/v1/tags/csv-import': typeof ApiV1TagsCsvImportRoute
  '/api/v1/tags/csv-mapping': typeof ApiV1TagsCsvMappingRouteWithChildren
  '/api/v1/tags/csv-parse': typeof ApiV1TagsCsvParseRoute
  '/api/v1/tags/csv-upload': typeof ApiV1TagsCsvUploadRoute
  '/api/v1/tags/reorder': typeof ApiV1TagsReorderRoute
  '/api/v1/transactions/$transactionId': typeof ApiV1TransactionsTransactionIdRouteWithChildren
  '/api/v1/transactions/bulk': typeof ApiV1TransactionsBulkRoute
  '/api/v1/transactions/csv-import': typeof ApiV1TransactionsCsvImportRoute
  '/api/v1/transactions/csv-mapping': typeof ApiV1TransactionsCsvMappingRouteWithChildren
  '/api/v1/transactions/csv-transform': typeof ApiV1TransactionsCsvTransformRoute
  '/api/v1/transactions/csv-upload': typeof ApiV1TransactionsCsvUploadRoute
  '/api/v1/me/accounts/$accountId': typeof ApiV1MeAccountsAccountIdRoute
  '/api/v1/tags/csv-mapping/validate': typeof ApiV1TagsCsvMappingValidateRoute
  '/api/v1/transactions/csv-mapping/validate': typeof ApiV1TransactionsCsvMappingValidateRoute
  '/api/v1/transactions/$transactionId/tags/$tagId': typeof ApiV1TransactionsTransactionIdTagsTagIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof appAccountRoute
  '/expenses': typeof appExpensesRoute
  '/incomes': typeof appIncomesRoute
  '/tags': typeof appTagsRoute
  '/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/transactions': typeof ApiV1TransactionsRouteWithChildren
  '/api/v1/me/accounts': typeof ApiV1MeAccountsRouteWithChildren
  '/api/v1/me/profile': typeof ApiV1MeProfileRoute
  '/api/v1/tags/$tagId': typeof ApiV1TagsTagIdRoute
  '/api/v1/tags/bulk': typeof ApiV1TagsBulkRoute
  '/api/v1/tags/csv-import': typeof ApiV1TagsCsvImportRoute
  '/api/v1/tags/csv-mapping': typeof ApiV1TagsCsvMappingRouteWithChildren
  '/api/v1/tags/csv-parse': typeof ApiV1TagsCsvParseRoute
  '/api/v1/tags/csv-upload': typeof ApiV1TagsCsvUploadRoute
  '/api/v1/tags/reorder': typeof ApiV1TagsReorderRoute
  '/api/v1/transactions/$transactionId': typeof ApiV1TransactionsTransactionIdRouteWithChildren
  '/api/v1/transactions/bulk': typeof ApiV1TransactionsBulkRoute
  '/api/v1/transactions/csv-import': typeof ApiV1TransactionsCsvImportRoute
  '/api/v1/transactions/csv-mapping': typeof ApiV1TransactionsCsvMappingRouteWithChildren
  '/api/v1/transactions/csv-transform': typeof ApiV1TransactionsCsvTransformRoute
  '/api/v1/transactions/csv-upload': typeof ApiV1TransactionsCsvUploadRoute
  '/api/v1/me/accounts/$accountId': typeof ApiV1MeAccountsAccountIdRoute
  '/api/v1/tags/csv-mapping/validate': typeof ApiV1TagsCsvMappingValidateRoute
  '/api/v1/transactions/csv-mapping/validate': typeof ApiV1TransactionsCsvMappingValidateRoute
  '/api/v1/transactions/$transactionId/tags/$tagId': typeof ApiV1TransactionsTransactionIdTagsTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/(app)/account': typeof appAccountRoute
  '/(app)/expenses': typeof appExpensesRoute
  '/(app)/incomes': typeof appIncomesRoute
  '/(app)/tags': typeof appTagsRoute
  '/(app)/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/transactions': typeof ApiV1TransactionsRouteWithChildren
  '/api/v1/me/accounts': typeof ApiV1MeAccountsRouteWithChildren
  '/api/v1/me/profile': typeof ApiV1MeProfileRoute
  '/api/v1/tags/$tagId': typeof ApiV1TagsTagIdRoute
  '/api/v1/tags/bulk': typeof ApiV1TagsBulkRoute
  '/api/v1/tags/csv-import': typeof ApiV1TagsCsvImportRoute
  '/api/v1/tags/csv-mapping': typeof ApiV1TagsCsvMappingRouteWithChildren
  '/api/v1/tags/csv-parse': typeof ApiV1TagsCsvParseRoute
  '/api/v1/tags/csv-upload': typeof ApiV1TagsCsvUploadRoute
  '/api/v1/tags/reorder': typeof ApiV1TagsReorderRoute
  '/api/v1/transactions/$transactionId': typeof ApiV1TransactionsTransactionIdRouteWithChildren
  '/api/v1/transactions/bulk': typeof ApiV1TransactionsBulkRoute
  '/api/v1/transactions/csv-import': typeof ApiV1TransactionsCsvImportRoute
  '/api/v1/transactions/csv-mapping': typeof ApiV1TransactionsCsvMappingRouteWithChildren
  '/api/v1/transactions/csv-transform': typeof ApiV1TransactionsCsvTransformRoute
  '/api/v1/transactions/csv-upload': typeof ApiV1TransactionsCsvUploadRoute
  '/api/v1/me/accounts/$accountId': typeof ApiV1MeAccountsAccountIdRoute
  '/api/v1/tags/csv-mapping/validate': typeof ApiV1TagsCsvMappingValidateRoute
  '/api/v1/transactions/csv-mapping/validate': typeof ApiV1TransactionsCsvMappingValidateRoute
  '/api/v1/transactions/$transactionId/tags/$tagId': typeof ApiV1TransactionsTransactionIdTagsTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/expenses'
    | '/incomes'
    | '/tags'
    | '/'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/tags'
    | '/api/v1/transactions'
    | '/api/v1/me/accounts'
    | '/api/v1/me/profile'
    | '/api/v1/tags/$tagId'
    | '/api/v1/tags/bulk'
    | '/api/v1/tags/csv-import'
    | '/api/v1/tags/csv-mapping'
    | '/api/v1/tags/csv-parse'
    | '/api/v1/tags/csv-upload'
    | '/api/v1/tags/reorder'
    | '/api/v1/transactions/$transactionId'
    | '/api/v1/transactions/bulk'
    | '/api/v1/transactions/csv-import'
    | '/api/v1/transactions/csv-mapping'
    | '/api/v1/transactions/csv-transform'
    | '/api/v1/transactions/csv-upload'
    | '/api/v1/me/accounts/$accountId'
    | '/api/v1/tags/csv-mapping/validate'
    | '/api/v1/transactions/csv-mapping/validate'
    | '/api/v1/transactions/$transactionId/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/expenses'
    | '/incomes'
    | '/tags'
    | '/'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/tags'
    | '/api/v1/transactions'
    | '/api/v1/me/accounts'
    | '/api/v1/me/profile'
    | '/api/v1/tags/$tagId'
    | '/api/v1/tags/bulk'
    | '/api/v1/tags/csv-import'
    | '/api/v1/tags/csv-mapping'
    | '/api/v1/tags/csv-parse'
    | '/api/v1/tags/csv-upload'
    | '/api/v1/tags/reorder'
    | '/api/v1/transactions/$transactionId'
    | '/api/v1/transactions/bulk'
    | '/api/v1/transactions/csv-import'
    | '/api/v1/transactions/csv-mapping'
    | '/api/v1/transactions/csv-transform'
    | '/api/v1/transactions/csv-upload'
    | '/api/v1/me/accounts/$accountId'
    | '/api/v1/tags/csv-mapping/validate'
    | '/api/v1/transactions/csv-mapping/validate'
    | '/api/v1/transactions/$transactionId/tags/$tagId'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/(app)/account'
    | '/(app)/expenses'
    | '/(app)/incomes'
    | '/(app)/tags'
    | '/(app)/'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/tags'
    | '/api/v1/transactions'
    | '/api/v1/me/accounts'
    | '/api/v1/me/profile'
    | '/api/v1/tags/$tagId'
    | '/api/v1/tags/bulk'
    | '/api/v1/tags/csv-import'
    | '/api/v1/tags/csv-mapping'
    | '/api/v1/tags/csv-parse'
    | '/api/v1/tags/csv-upload'
    | '/api/v1/tags/reorder'
    | '/api/v1/transactions/$transactionId'
    | '/api/v1/transactions/bulk'
    | '/api/v1/transactions/csv-import'
    | '/api/v1/transactions/csv-mapping'
    | '/api/v1/transactions/csv-transform'
    | '/api/v1/transactions/csv-upload'
    | '/api/v1/me/accounts/$accountId'
    | '/api/v1/tags/csv-mapping/validate'
    | '/api/v1/transactions/csv-mapping/validate'
    | '/api/v1/transactions/$transactionId/tags/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1MeRoute: typeof ApiV1MeRouteWithChildren
  ApiV1TagsRoute: typeof ApiV1TagsRouteWithChildren
  ApiV1TransactionsRoute: typeof ApiV1TransactionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tags': {
      id: '/(app)/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof appTagsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/incomes': {
      id: '/(app)/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof appIncomesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/expenses': {
      id: '/(app)/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof appExpensesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/account': {
      id: '/(app)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appAccountRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/v1/transactions': {
      id: '/api/v1/transactions'
      path: '/api/v1/transactions'
      fullPath: '/api/v1/transactions'
      preLoaderRoute: typeof ApiV1TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tags': {
      id: '/api/v1/tags'
      path: '/api/v1/tags'
      fullPath: '/api/v1/tags'
      preLoaderRoute: typeof ApiV1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/transactions/csv-upload': {
      id: '/api/v1/transactions/csv-upload'
      path: '/csv-upload'
      fullPath: '/api/v1/transactions/csv-upload'
      preLoaderRoute: typeof ApiV1TransactionsCsvUploadRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/transactions/csv-transform': {
      id: '/api/v1/transactions/csv-transform'
      path: '/csv-transform'
      fullPath: '/api/v1/transactions/csv-transform'
      preLoaderRoute: typeof ApiV1TransactionsCsvTransformRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/transactions/csv-mapping': {
      id: '/api/v1/transactions/csv-mapping'
      path: '/csv-mapping'
      fullPath: '/api/v1/transactions/csv-mapping'
      preLoaderRoute: typeof ApiV1TransactionsCsvMappingRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/transactions/csv-import': {
      id: '/api/v1/transactions/csv-import'
      path: '/csv-import'
      fullPath: '/api/v1/transactions/csv-import'
      preLoaderRoute: typeof ApiV1TransactionsCsvImportRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/transactions/bulk': {
      id: '/api/v1/transactions/bulk'
      path: '/bulk'
      fullPath: '/api/v1/transactions/bulk'
      preLoaderRoute: typeof ApiV1TransactionsBulkRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/transactions/$transactionId': {
      id: '/api/v1/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/api/v1/transactions/$transactionId'
      preLoaderRoute: typeof ApiV1TransactionsTransactionIdRouteImport
      parentRoute: typeof ApiV1TransactionsRoute
    }
    '/api/v1/tags/reorder': {
      id: '/api/v1/tags/reorder'
      path: '/reorder'
      fullPath: '/api/v1/tags/reorder'
      preLoaderRoute: typeof ApiV1TagsReorderRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/csv-upload': {
      id: '/api/v1/tags/csv-upload'
      path: '/csv-upload'
      fullPath: '/api/v1/tags/csv-upload'
      preLoaderRoute: typeof ApiV1TagsCsvUploadRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/csv-parse': {
      id: '/api/v1/tags/csv-parse'
      path: '/csv-parse'
      fullPath: '/api/v1/tags/csv-parse'
      preLoaderRoute: typeof ApiV1TagsCsvParseRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/csv-mapping': {
      id: '/api/v1/tags/csv-mapping'
      path: '/csv-mapping'
      fullPath: '/api/v1/tags/csv-mapping'
      preLoaderRoute: typeof ApiV1TagsCsvMappingRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/csv-import': {
      id: '/api/v1/tags/csv-import'
      path: '/csv-import'
      fullPath: '/api/v1/tags/csv-import'
      preLoaderRoute: typeof ApiV1TagsCsvImportRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/bulk': {
      id: '/api/v1/tags/bulk'
      path: '/bulk'
      fullPath: '/api/v1/tags/bulk'
      preLoaderRoute: typeof ApiV1TagsBulkRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/tags/$tagId': {
      id: '/api/v1/tags/$tagId'
      path: '/$tagId'
      fullPath: '/api/v1/tags/$tagId'
      preLoaderRoute: typeof ApiV1TagsTagIdRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/me/profile': {
      id: '/api/v1/me/profile'
      path: '/profile'
      fullPath: '/api/v1/me/profile'
      preLoaderRoute: typeof ApiV1MeProfileRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/me/accounts': {
      id: '/api/v1/me/accounts'
      path: '/accounts'
      fullPath: '/api/v1/me/accounts'
      preLoaderRoute: typeof ApiV1MeAccountsRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/transactions/csv-mapping/validate': {
      id: '/api/v1/transactions/csv-mapping/validate'
      path: '/validate'
      fullPath: '/api/v1/transactions/csv-mapping/validate'
      preLoaderRoute: typeof ApiV1TransactionsCsvMappingValidateRouteImport
      parentRoute: typeof ApiV1TransactionsCsvMappingRoute
    }
    '/api/v1/tags/csv-mapping/validate': {
      id: '/api/v1/tags/csv-mapping/validate'
      path: '/validate'
      fullPath: '/api/v1/tags/csv-mapping/validate'
      preLoaderRoute: typeof ApiV1TagsCsvMappingValidateRouteImport
      parentRoute: typeof ApiV1TagsCsvMappingRoute
    }
    '/api/v1/me/accounts/$accountId': {
      id: '/api/v1/me/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/api/v1/me/accounts/$accountId'
      preLoaderRoute: typeof ApiV1MeAccountsAccountIdRouteImport
      parentRoute: typeof ApiV1MeAccountsRoute
    }
    '/api/v1/transactions/$transactionId/tags/$tagId': {
      id: '/api/v1/transactions/$transactionId/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/api/v1/transactions/$transactionId/tags/$tagId'
      preLoaderRoute: typeof ApiV1TransactionsTransactionIdTagsTagIdRouteImport
      parentRoute: typeof ApiV1TransactionsTransactionIdRoute
    }
  }
}

interface appRouteRouteChildren {
  appAccountRoute: typeof appAccountRoute
  appExpensesRoute: typeof appExpensesRoute
  appIncomesRoute: typeof appIncomesRoute
  appTagsRoute: typeof appTagsRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAccountRoute: appAccountRoute,
  appExpensesRoute: appExpensesRoute,
  appIncomesRoute: appIncomesRoute,
  appTagsRoute: appTagsRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface ApiV1MeAccountsRouteChildren {
  ApiV1MeAccountsAccountIdRoute: typeof ApiV1MeAccountsAccountIdRoute
}

const ApiV1MeAccountsRouteChildren: ApiV1MeAccountsRouteChildren = {
  ApiV1MeAccountsAccountIdRoute: ApiV1MeAccountsAccountIdRoute,
}

const ApiV1MeAccountsRouteWithChildren = ApiV1MeAccountsRoute._addFileChildren(
  ApiV1MeAccountsRouteChildren,
)

interface ApiV1MeRouteChildren {
  ApiV1MeAccountsRoute: typeof ApiV1MeAccountsRouteWithChildren
  ApiV1MeProfileRoute: typeof ApiV1MeProfileRoute
}

const ApiV1MeRouteChildren: ApiV1MeRouteChildren = {
  ApiV1MeAccountsRoute: ApiV1MeAccountsRouteWithChildren,
  ApiV1MeProfileRoute: ApiV1MeProfileRoute,
}

const ApiV1MeRouteWithChildren =
  ApiV1MeRoute._addFileChildren(ApiV1MeRouteChildren)

interface ApiV1TagsCsvMappingRouteChildren {
  ApiV1TagsCsvMappingValidateRoute: typeof ApiV1TagsCsvMappingValidateRoute
}

const ApiV1TagsCsvMappingRouteChildren: ApiV1TagsCsvMappingRouteChildren = {
  ApiV1TagsCsvMappingValidateRoute: ApiV1TagsCsvMappingValidateRoute,
}

const ApiV1TagsCsvMappingRouteWithChildren =
  ApiV1TagsCsvMappingRoute._addFileChildren(ApiV1TagsCsvMappingRouteChildren)

interface ApiV1TagsRouteChildren {
  ApiV1TagsTagIdRoute: typeof ApiV1TagsTagIdRoute
  ApiV1TagsBulkRoute: typeof ApiV1TagsBulkRoute
  ApiV1TagsCsvImportRoute: typeof ApiV1TagsCsvImportRoute
  ApiV1TagsCsvMappingRoute: typeof ApiV1TagsCsvMappingRouteWithChildren
  ApiV1TagsCsvParseRoute: typeof ApiV1TagsCsvParseRoute
  ApiV1TagsCsvUploadRoute: typeof ApiV1TagsCsvUploadRoute
  ApiV1TagsReorderRoute: typeof ApiV1TagsReorderRoute
}

const ApiV1TagsRouteChildren: ApiV1TagsRouteChildren = {
  ApiV1TagsTagIdRoute: ApiV1TagsTagIdRoute,
  ApiV1TagsBulkRoute: ApiV1TagsBulkRoute,
  ApiV1TagsCsvImportRoute: ApiV1TagsCsvImportRoute,
  ApiV1TagsCsvMappingRoute: ApiV1TagsCsvMappingRouteWithChildren,
  ApiV1TagsCsvParseRoute: ApiV1TagsCsvParseRoute,
  ApiV1TagsCsvUploadRoute: ApiV1TagsCsvUploadRoute,
  ApiV1TagsReorderRoute: ApiV1TagsReorderRoute,
}

const ApiV1TagsRouteWithChildren = ApiV1TagsRoute._addFileChildren(
  ApiV1TagsRouteChildren,
)

interface ApiV1TransactionsTransactionIdRouteChildren {
  ApiV1TransactionsTransactionIdTagsTagIdRoute: typeof ApiV1TransactionsTransactionIdTagsTagIdRoute
}

const ApiV1TransactionsTransactionIdRouteChildren: ApiV1TransactionsTransactionIdRouteChildren =
  {
    ApiV1TransactionsTransactionIdTagsTagIdRoute:
      ApiV1TransactionsTransactionIdTagsTagIdRoute,
  }

const ApiV1TransactionsTransactionIdRouteWithChildren =
  ApiV1TransactionsTransactionIdRoute._addFileChildren(
    ApiV1TransactionsTransactionIdRouteChildren,
  )

interface ApiV1TransactionsCsvMappingRouteChildren {
  ApiV1TransactionsCsvMappingValidateRoute: typeof ApiV1TransactionsCsvMappingValidateRoute
}

const ApiV1TransactionsCsvMappingRouteChildren: ApiV1TransactionsCsvMappingRouteChildren =
  {
    ApiV1TransactionsCsvMappingValidateRoute:
      ApiV1TransactionsCsvMappingValidateRoute,
  }

const ApiV1TransactionsCsvMappingRouteWithChildren =
  ApiV1TransactionsCsvMappingRoute._addFileChildren(
    ApiV1TransactionsCsvMappingRouteChildren,
  )

interface ApiV1TransactionsRouteChildren {
  ApiV1TransactionsTransactionIdRoute: typeof ApiV1TransactionsTransactionIdRouteWithChildren
  ApiV1TransactionsBulkRoute: typeof ApiV1TransactionsBulkRoute
  ApiV1TransactionsCsvImportRoute: typeof ApiV1TransactionsCsvImportRoute
  ApiV1TransactionsCsvMappingRoute: typeof ApiV1TransactionsCsvMappingRouteWithChildren
  ApiV1TransactionsCsvTransformRoute: typeof ApiV1TransactionsCsvTransformRoute
  ApiV1TransactionsCsvUploadRoute: typeof ApiV1TransactionsCsvUploadRoute
}

const ApiV1TransactionsRouteChildren: ApiV1TransactionsRouteChildren = {
  ApiV1TransactionsTransactionIdRoute:
    ApiV1TransactionsTransactionIdRouteWithChildren,
  ApiV1TransactionsBulkRoute: ApiV1TransactionsBulkRoute,
  ApiV1TransactionsCsvImportRoute: ApiV1TransactionsCsvImportRoute,
  ApiV1TransactionsCsvMappingRoute:
    ApiV1TransactionsCsvMappingRouteWithChildren,
  ApiV1TransactionsCsvTransformRoute: ApiV1TransactionsCsvTransformRoute,
  ApiV1TransactionsCsvUploadRoute: ApiV1TransactionsCsvUploadRoute,
}

const ApiV1TransactionsRouteWithChildren =
  ApiV1TransactionsRoute._addFileChildren(ApiV1TransactionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1MeRoute: ApiV1MeRouteWithChildren,
  ApiV1TagsRoute: ApiV1TagsRouteWithChildren,
  ApiV1TransactionsRoute: ApiV1TransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
